id: PBF29AA99
initial_creation_type: input
source_metadata:
  title: Tattvopaplavasiṃha
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy
  data entry: Somadeva Vasudeva
  contribution to GRETIL: Somadeva Vasudeva
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:27:00.989323'
last_modified_at: '2022-03-09T15:27:00.989335'
